### ISSUE TITLE
安装第4部出错

### ISSUE THREAD

**Issue by JackWang1024** [redsx/myBlog#1]
run webpack 在git bash里面的具体命令行是什么？（命令出错，安装失败。）过后知道问题出在电脑重新安装win7系统后，node安装在系统默认路径Program Files下，git bash对路径文件夹空格不识别，get prefix 的path 错误所致，谢谢。

**Comment by redsx** [comment]
运行webpack就行了

**Comment by wonyun** [comment]
没用过webpack，如何运行webpack？请指教

**Comment by redsx** [comment]
直接在iterm里边敲webpack就行
